### ISSUE TITLE
Rendre libre le type de la livraison effectué

### ISSUE THREAD

**Issue by CorentinPeutin** [Geoplateforme/sdk-entrepot#117]
Bonjour,

Lorsque l'on souhaite livrer une donnée avec le SDK, le type de la livraison définit dans le descripteur doit correspondre obligatoirement certaines valeurs ("RASTER", "VECTOR", "ARCHIVE" et peut-être d'autres).
Mais cela empêche de faire des livraisons pour d'autres types comme par exemple le type INDEX utile pour le service de recherche. Et, au fil des évolutions, il est possible que de nouveaux types de livraison apparaissent.
Est-ce qu'il ne serait donc pas plus intéressant de laisser la possibilité à l'utilisateur de mettre le type qu'il souhaite et laisser l'API renvoyer une erreur si le type n'existe pas ?

Merci

**Comment by LudivineSchlegel** [comment]
@CorentinPeutin le type la livraison n'est plus limité avec le version v0.1.26
Je vous laisse fermer le ticket si la solution conviens.

**Comment by CorentinPeutin** [comment]
Il est bien possible de livrer n'importe quel type de données.
Mais je viens de me rendre compte que, dans le cas de la livraison d'INDEX, il est possible de préciser un paramètre supplémentaire dans la livraison : 'type_infos': {'is_search_layer': True}. Et il n'est pas possible d'ajouter ce paramètre dans le descripteur de la livraison.
Est-ce qu'il serait donc possible de permettre l'utilisation de ce paramètre dans le descripteur de la livraison ?

**Comment by LudivineSchlegel** [comment]
Correction en cours #133.
Nous n'avons pas été averti de l'ajout du paramètre `type_infos` dans le requête de déclaration une nouvelle livraison.

**Comment by LudivineSchlegel** [comment]
La correction sera disponible dans la version v0.1.27

**Comment by LudivineSchlegel** [comment]
Bonjour @CorentinPeutin 
Le correction pour le paramètre `type_infos` est disponible dans le nouvelle version v0.1.27.
Si la correction vous conviens je vous laisse fermer le ticket.

**Comment by CorentinPeutin** [comment]
Dans le cas d'un index de recherche, la livraison fonctionne bien. Merci beaucoup
