### ISSUE TITLE
amélioration commande workflow dans précision étape

### ISSUE THREAD

**Issue by LudivineSchlegel** [Geoplateforme/sdk-entrepot#12]
il serait bien que en plus de vérifier le workflow on ait la liste des étapes possibles + parent si donnés. Ce qui permettrait de plus facilement retrouver les étapes du workflow à mettre dans la commande.

```sh
python -m ignf_gpf_sdk workflow -f wfs-generic.jsonc
```

**Comment by Alain2023** [comment]
$ python3 -m ignf_gpf_sdk workflow -f ignf_gpf_sdk/_data/workflows/generic_joincache.jsonc 

INFO - Ouverture du workflow /home/AMaria-Admin/git/ignf-gpf-sdk/ignf_gpf_sdk/_data/workflows/generic_joincache.jsonc...
INFO - Validation du workflow...
INFO - Le workflow est valide.
INFO - Liste des étapes disponibles et de leurs parents :
INFO -    * Etape « pyramide1 » [parent(s) : ]
INFO -    * Etape « configuration-WMST-pyramide1 » [parent(s) : pyramide1]
INFO -    * Etape « publication-WMST-pyramide1 » [parent(s) : configuration-WMST-pyramide1]
INFO -    * Etape « pyramide2 » [parent(s) : ]
INFO -    * Etape « fusion-pyramide » [parent(s) : pyramide1, pyramide2]
INFO -    * Etape « configuration-WMS-pyramide-fusion » [parent(s) : fusion-pyramide]
INFO -    * Etape « publication-WMS-pyramide-fusion » [parent(s) : configuration-WMS-pyramide-fusion]
INFO -    * Etape « injection-pyramide » [parent(s) : pyramide1]

**Comment by vsasyan-ignf** [comment]
fait
