### ISSUE TITLE
Ajout de la route patch pour les stored data

### ISSUE THREAD

**Issue by mmohadIGN** [Geoplateforme/sdk-entrepot#129]
## Intitulé

* En tant qu'utilisateur
* Je veux  edité ma stored data
* Afin de spécifier les champs description, édition et extent

## Spécifications

    La route est la suivante : /datastores/{{ datastore }}/stored_data/{{ _.stored_data_2 }}
Et le corps de la requete suit le schéma suivant : 
`{
						"description" : "Extrait des couches vecteur de la BD TOPO V3 sur la commune de La Ciotat. Sélection de couches.",
  "edition": {
    "from": "2024-01-01",
    "to": "2024-01-02"
  },
  "extent": { "type": "Polygon", "coordinates": [ [ [ 5.619235887613368, 43.157384856711388 ], [ 5.619184395498695, 43.157387907511811 ], [ 5.604675214299569, 43.160254767064018 ], [ 5.572516849497754, 43.172817929010172 ], [ 5.572302495939968, 43.17291933679109 ], [ 5.57199111557705, 43.173133752321945 ], [ 5.570161206115586, 43.174482308550154 ], [ 5.569431862789132, 43.175114354976095 ], [ 5.569286373818453, 43.175243814459876 ], [ 5.56164802862615, 43.182070761768166 ], [ 5.557226220395084, 43.186554868213321 ], [ 5.556061839707134, 43.188285184428878 ], [ 5.555964885368623, 43.18845667381472 ], [ 5.562694363127019, 43.197866336835851 ], [ 5.565908384440696, 43.20104333972801 ], [ 5.592452402722978, 43.218798267117002 ], [ 5.59392033162109, 43.218849396938325 ], [ 5.595529992178347, 43.218905198482986 ], [ 5.678373607569832, 43.216648877167437 ], [ 5.679119842319442, 43.208651656994903 ], [ 5.67617511011226, 43.189823585814956 ], [ 5.676082711182597, 43.189289475372284 ], [ 5.675764857743051, 43.187950954604467 ], [ 5.675676317858941, 43.187579649570296 ], [ 5.675637712150082, 43.187436606710975 ], [ 5.675580137099572, 43.18722923418408 ], [ 5.674811638642257, 43.185135989503742 ], [ 5.673136582544351, 43.180912420319295 ], [ 5.672910865658308, 43.180499515657957 ], [ 5.672862502826696, 43.18043771439828 ], [ 5.672844265236997, 43.18041566643344 ], [ 5.672499583688224, 43.180036309075412 ], [ 5.672082079912086, 43.179624555156153 ], [ 5.671930787136983, 43.179517603774535 ], [ 5.619285127573667, 43.157386360394845 ], [ 5.619235887613368, 43.157384856711388 ] ] ] } 
}`

## Critères d'acceptation

-[] je peux éditer ma stored data aprés sa création

## Commentaires

Bloquer par la recette encore en qua

**Comment by LudivineSchlegel** [comment]
L'action d'édition partiel d'une stored data été disponible. Seule la configuration de la route n'était pas faite : `stored_data_partial_edit=${stored_data_get}`
Suite à la vérification des routes il manque aussi la route `upload_partial_edit=${upload_get}`

Je pousse ces deux routes pour la prochaine version du SDK.

**Comment by LudivineSchlegel** [comment]
@mmohadIGN l'url pour l'édition partiel d'une stored_data à été ajouté dans le version v0.1.26.
Je vous laisse fermer si la solution conviens
