### ISSUE TITLE
Listing des programmes qui n'ont pas d'entête ou qui ont des informations manquantes dans l'entête

### ISSUE THREAD

**Issue by fbacquelot** [Geoplateforme/sdk-entrepot#137]

**Comment by fbacquelot** [comment]
* Projet **sdk entrepôt de la géoplateforme** : 
* dans le dossier courant : 
- [ ]  **check.sh**, => pas d'entête fournie.
* dans le dossier **docker** : 
- [ ]  **Dockerfile** => pas d'entête fournie.
* dans le sous-dossier **sdk_entreepot_gpf** : 
- [ ] **Errors.py** => manque contexte, les entrées sorties et les entêtes des méthodes. 
* dans le sous-dossier **sdk_entrepot_gpf/auth** : 
- [ ]  **Authentifier.py** => pas d'entête fournie.
- [ ]  **Errors.py** => pas d'entête fournie.
- [ ]  **Token.py** => pas d'entête fournie, mais informations ok.
* dans le sous-dossier **sdk_entrepot_gpf/helper** : 
- [ ] **FileHelper.py**=> pas d'entête fournie, mais but ok.
- [ ] **JsonHelper.py**=> pas d'entête fournie, mais but ok.
- [ ] **PrintLogHelper.py**=> pas d'entête fournie, mais but ok.
* dans le sous-dossier **sdk_entrepot_gpf/io** : 
- [ ]  **ApiRequester.py** => pas d'entête fournie, mais but ok.
- [ ] **JsonConverter.py** => manque les entrées/sorties.
* dans le sous-dossier **sdk_entrepot_gpf/pattern** : 
- [ ] **SingleInstance.py** => pas d'entête fournie, manque les entrées/sorties.
- [ ] **Singleton.py** => pas d'entête fournie, manque les entrées/sorties.
* dans le sous-dossier **sdk_entrepot_gpf/store** : 
- [ ] **AbstractCommonFile.py** => pas d'entête fournie, et manque aussi le type des arguments d'entrée et de sortie de la classe.
- [ ] **Annexe.py** => pas d'entête fournie, mais but ok.
- [ ] **Check.py** => pas d'entête fournie, mais but ok.
- [ ] **CheckExecution.py** => pas d'entête fournie, mais but ok.
- [ ] **Configuration.py** => pas d'entête fournie, mais but ok.
- [ ] **Datastore.py** => pas d'entête fournie, mais but ok.
- [ ] **Endpoint.py** => pas d'entête fournie, mais but ok.
- [ ] **Errors.py** => pas d'entête fournie, mais but ok.
- [ ] **Metadata.py** => pas d'entête fournie, mais but ok.
- [ ] **Offering.py** => pas d'entête fournie, mais but ok.
- [ ] **Permission.py** => pas d'entête fournie, mais but ok.
- [ ] **Processing.py** => pas d'entête fournie, mais but ok.
- [ ] **ProcessingExceution.py** => pas d'entête fournie, mais but ok.
- [ ] **Static.py** => pas d'entête fournie, mais but ok.
- [ ] **StoreEntity.py** => pas d'entête fournie, mais but ok.
- [ ] **StoredData.py** => pas d'entête fournie, mais but ok.
- [ ] **Tms.py** => pas d'entête fournie, mais but ok.
- [ ] **Upload.py** => pas d'entête fournie, mais but ok.
- [ ] **User.py** => pas d'entête fournie, mais but ok.
* dans le sous-dossier **sdk_entrepot_gpf/workflow** : 
- [ ] **Errors.py** => pas d'entête fournie, mais but ok. manque aussi une entête à une méthode.
- [ ] **Workflow.py** => pas d'entête fournie, mais but ok. manque aussi des entêtes à certaines méthodes de la classe.
* dans le sous-dossier **sdk_entrepot_gpf/workflow/action** : 
- [ ] 
* dans le sous-dossier **sdk_entrepot_gpf/workflow/resolver** :
- [ ]

**Comment by LudivineSchlegel** [comment]
Dossier publique il ne doit pas avoir d'entête IGN
