### ISSUE TITLE
upload en erreur : champ datastore a une valeur invalide String au lieu de UUID

### ISSUE THREAD

**Issue by EB6TLS** [Geoplateforme/sdk-entrepot#156]
```sh
python3 -m sdk_entrepot_gpf  --debug --ini config_dinamis.ini upload -f /Volumes/Mabele/PROJETS/GPI/BAG/DATA/PAQUETS/BEZIERS-COLOMBIERS_2022110638503087/upload-dinamis.json
```
entraine la réponse suivante : 

```
INFO - LIVRAISONS : (1)
INFO -  * ORTHO-SAT-0M50_1-0_TIF_LAMB93_BEZIERS-COLOMBIERS_2022110638503087_RVB_8bits_2024-04-03
INFO - Création et complétion d'une livraison...
INFO - Création d'une livraison...
DEBUG - route_request(upload_list, GET, {'datastore': None}, {'name': 'ORTHO-SAT-0M50_1-0_TIF_LAMB93_BEZIERS-COLOMBIERS_2022110638503087_RVB_8bits_2024-04-03', 'page': 1, 'limit': 10})
DEBUG - url_request(https://data.geopf.fr/api/datastores/DATASTORE_ID_TO_MODIFY/uploads, GET, {'name': 'ORTHO-SAT-0M50_1-0_TIF_LAMB93_BEZIERS-COLOMBIERS_2022110638503087_RVB_8bits_2024-04-03', 'page': 1, 'limit': 10}, None)
DEBUG - __url_request(https://data.geopf.fr/api/datastores/DATASTORE_ID_TO_MODIFY/uploads, GET, {'name': 'ORTHO-SAT-0M50_1-0_TIF_LAMB93_BEZIERS-COLOMBIERS_2022110638503087_RVB_8bits_2024-04-03', 'page': 1, 'limit': 10}, None, None)
ERREUR - livraison ORTHO-SAT-0M50_1-0_TIF_LAMB93_BEZIERS-COLOMBIERS_2022110638503087_RVB_8bits_2024-04-03 : La requête formulée par le programme est incorrecte (Le champ datastore a une valeur invalide String, le type attendu est UUID). Contactez le support.
```

alors que la commande suivante répond comme attendu

```sh
python3 -m sdk_entrepot_gpf  --debug --ini /Volumes/Mabele/PROJETS/GPI/BAG/TP/config_dinamis.ini me
```

```
DEBUG - route_request(me_get, GET, None, None)
DEBUG - url_request(https://data.geopf.fr/api/users/me, GET, None, None)
DEBUG - __url_request(https://data.geopf.fr/api/users/me, GET, None, None, None)
Vos informations :
  * email : eric.breton@ign.fr
  * nom : Eric Breton
  * votre id : e9fa8933-f8e0-XXXXX-6b5e5646cb1f

Vous êtes membre de 1 communauté(s) :

  * communauté « DINAMIS » :
      - id de la communauté : f01bfb78-XXX-109455091410
      - id du datastore : f769c305-YYYY-9701478e17b7
      - nom technique : dinamis
      - droits : ANNEX, COMMUNITY, UPLOAD, PROCESSING, BROADCAST
[test_archive.zip](https://github.com/user-attachments/files/15952641/test_archive.zip)
```

**Comment by LudivineSchlegel** [comment]
Bonjour,

Vous avez un problème avec votre configuration, il manque l'id du datastore :
> https://data.geopf.fr/api/datastores/ **DATASTORE_ID_TO_MODIFY** /uploads,

Dans votre fichier de configuration `config_dinamis.ini`, il faut rajouter l'identifiant du datastore à utilisé :
```ini
[store_api]
# L'identifiant de votre entrepôt
datastore=f769c305-YYYY-9701478e17b7
```

Ou le préciser dans la ligne de commande:
`python3 -m sdk_entrepot_gpf --debug --ini config_dinamis.ini upload  --datastore f769c305-YYYY-9701478e17b7 -f /Volumes/Mabele/PROJETS/GPI/BAG/DATA/PAQUETS/BEZIERS-COLOMBIERS_2022110638503087/upload-dinamis.json`

Si vous utilisez toujours le même datastore je vous conseille l'ajout à la configuration plutôt que de préciser à chaque ligne de commande le datastore.

**Comment by vsasyan-ignf** [comment]
@EB6TLS @LudivineSchlegel @mmohadIGN je supprime le ticket car il y a des informations en clair dans l'historique des tickets.

**Comment by vsasyan-ignf** [comment]
@EB6TLS il faut bien mettre la clef `datastore` dans la section `store_api` :

```
[store_api]
# L'identifiant de votre entrepôt
datastore=f769c305-YYYY-9701478e17b7
```

**Comment by EB6TLS** [comment]
merci de vos lumières. Le transfert des données est effectué.

INFO - Vérifications : 0 en attente, 0 en cours, 0 en échec, 1 en succès
INFO - Livraison Upload(id=bab62248-bcf8-4e66-9ba1-6837b7a8d7ac, name=ORTHO-SAT-0M50_1-0_TIF_LAMB93_BEZIERS-COLOMBIERS_2022110638503087_RVB_8bits_2024-04-03) créée avec succès.
INFO - Fin des vérifications.
INFO - ----------------------------------------------------------------------------------------------------
INFO - BILAN : les 1 livraisons se sont bien passées
