### ISSUE TITLE
Le transfert de fichiers xml ou zip pour une livraison de type RASTER semble générer des erreurs internes

### ISSUE THREAD

**Issue by nick-rv** [Geoplateforme/sdk-entrepot#171]
La livraison contient des images type tif/cog qui semblen correctement être transférer pendant la création d'une livraison de type RASTER avec la commande upload du sdk.

Cependant lors du transfert de fichiers autres que les images, de type ZIP et XML, ceci génère des erreurs.
C'est peut-être normal, confirmez-vous ?
S'agit-il d'un contrôle effectué par le SDK ?

Est-ce que le comportement paramétrable le cas échéant afin d'autoriser telle ou telle extension : au niveau SDK ou au niveau API ?

Voici le fichier de configuration de la livraison et les logs en debug attachés.
[log_upload_raster_xml.txt](https://github.com/user-attachments/files/16453843/log_upload_raster_xml.txt)
[LITTORAL-FORESTIER-LES-SABLES-D-OLONNE_2024062740987230_upload_flux.json](https://github.com/user-attachments/files/16453880/LITTORAL-FORESTIER-LES-SABLES-D-OLONNE_2024062740987230_upload_flux.json)

Merci d'avance

**Comment by LudivineSchlegel** [comment]
Bonjour,
L'erreur ne viens pas du SDK mais de l'API GPF qui retourne un code erreur 500 (InternalServerError).
Côté SDK nous ne faisons aucune vérification sur les extensions, les contrôles sont fait par l'API GPF.

J'ai testé avec un upload de type RASTER, j'ai pu livrer des données de type ZIP et XML. Le problème viens probablement d'une instabilité de la GPF au moment de la livraison.

Si vous relancer la commande l'upload devrait bien se passé.
Si besoin il est possible de tester directement avec le swagger : https://data.geopf.fr/api/swagger-ui/index.html#/Livraisons%20et%20v%C3%A9rifications/uploadData

**Comment by nick-rv** [comment]
Bonjour merci pour le retour!
En fait c'est visiblement la longueur du chemin utilisé pour le transert des fichiers qui est trop long!
Du coup désolé pour le dérangement.
Je pense qu'il faut ouvrir un bug côté entrepôt car un code retour 400 serait plus logique que 500 dans ce cas.
Merci, le sujet est clos côté SDK!
