### ISSUE TITLE
Que doit-on mettre dans client_id de config.ini ?

### ISSUE THREAD

**Issue by jpotel** [Geoplateforme/sdk-entrepot#37]
Bonjour
faut-il maintenir `id_client=pf-warehouses` dans config.ini pour une connexion à l'API ?
Je n'ai jamais réussi à avoir le résultat du `python -m ignf_gpf_sdk me` en suivant la syntaxe du config.ini proposé dans la documentation.
Cordialement

**Comment by jpotel** [comment]
voici les info retournées par la commande : 
```
←[33mALERTE - Code retour authentification KeyCloak = 401 (Invalid client or Invalid client credentials)←[0m
←[33mALERTE - Code retour authentification KeyCloak = 401 (Invalid client or Invalid client credentials)←[0m
←[33mALERTE - Code retour authentification KeyCloak = 401 (Invalid client or Invalid client credentials)←[0m
←[33mALERTE - Code retour authentification KeyCloak = 401 (Invalid client or Invalid client credentials)←[0m
←[33mALERTE - Code retour authentification KeyCloak = 401 (Invalid client or Invalid client credentials)←[0m
←[33mALERTE - Code retour authentification KeyCloak = 401 (Invalid client or Invalid client credentials)←[0m
←[31mERREUR - La récupération du jeton d'authentification a échoué après 5 tentatives←[0m
←[31mERREUR - La récupération du jeton d'authentification a échoué après 5 tentatives←[0m
←[31mERREUR FATALE - La récupération du jeton d'authentification a échoué après 5 tentatives←[0m
```

**Comment by jpotel** [comment]
J'ai trouvé, il faut renseigner le paramètre client_secret.
il serait bien d'indiquer dans la partie doc relative à la génération du config.ini la façon de trouver ce client_secret et de le rajouter le config.ini

**Comment by jmkerloch** [comment]
@jpotel à quoi correspond le paramètre client_secret ? Je ne sais pas comment le trouver.

**Comment by vsasyan-ignf** [comment]
Bonjour @jpotel et @jmkerloch,

Désolé pour le temps de réponse, je n'ai pas reçu les notifications. N'hésitez pas à m'assigner à l'issue ou à me taguer au bout de quelques jours sans retour de ma part.

> il serait bien d'indiquer dans la partie doc relative à la génération du config.ini la façon de trouver ce client_secret et de le rajouter le config.ini

Merci pour le retour, nous allons compléter cela. Est-ce que vous pouvez m'indiquer comment vous avez récupéré l'information dans votre cas ?
Effectivement, notre cas est un peu spécial, on nous l'a donné à la création de notre compte, mais ce n'est pas forcément pareil pour vous.

Cordialement,

**Comment by jmkerloch** [comment]
Je travaille actuellement sur la geoplateforme via mon entreprise Oslandia. J'ai pu avoir l'information via un canal de communication des entreprises du groupement.

**Comment by jpotel** [comment]
Pour ma part je l'ai récupéré de deux façons : 
- il est en clair dans une video d'un des tutoriels geoplateforme : https://geoplateforme.github.io/tutoriels/production/controle-des-acces/entrepot/connexion_fme/
- en utilisant l'outil de développement de chrome sur la page de demande de connexion de swagger

**Comment by vsasyan-ignf** [comment]
Merci pour vos retours. Donc on doit l'avoir avec les informations communiquées à la création du compte.

**Comment by vsasyan-ignf** [comment]
Bonjour,

Après confirmation le client sercret est donc toujours le même et c'est : `BK2G7Vvkn7UDc8cV7edbCnHdYminWVw2` en prod

**Comment by vsasyan-ignf** [comment]
@LudivineSchlegel à ajouter dans la doc de la config STP.

**Comment by LudivineSchlegel** [comment]
v0.1.19 : Documentation ajouté dans la doc et les valeurs sont inscrites dans le fichier de configuration par défaut.
