### ISSUE TITLE
Upload impossible sur l'environnement de qualification

### ISSUE THREAD

**Issue by jmkerloch** [Geoplateforme/sdk-entrepot#54]
Depuis la dernière mise à jour de l'environnement de qualification il n'est plus possible de créer d'upload:

> 
> ERREUR - La requête formulée par le programme est incorrecte (Le query param path est absent ou mal formaté). Contactez le support.
> Traceback (most recent call last):
>   File "/home/jmkerloch/dev/ign/gpf-iti-scripts/.venv/lib/python3.10/site-packages/sdk_entrepot_gpf/io/ApiRequester.py", line 134, in url_request
>     return self.__url_request(url, method, params=params, data=data, files=files, header=header)
>   File "/home/jmkerloch/dev/ign/gpf-iti-scripts/.venv/lib/python3.10/site-packages/sdk_entrepot_gpf/io/ApiRequester.py", line 248, in __url_request
>     raise BadRequestError(url, method, params, data, r.text)
> sdk_entrepot_gpf.io.Errors.BadRequestError: Erreur au requêtage de la Géoplateforme.
> Explication : Erreur API : mauvaise requête (contactez le support).
> Détails : 
>    * url: https://data-qua.priv.geopf.fr/api/datastores/552d3096-0df9-4107-9e48-85ff0620af4e/uploads/b5d9504b-8d04-44bc-91a4-c809de9ead7e/data
>    * method: POST
>    * params: {'path': 'bdtopo/BDTOPO_TRANSPORT_PARIS.gpkg'}
>    * data: null
>    * response: {"error":"Bad Request","error_description":["Le query param path est absent ou mal formaté"]}
>    * error: Bad Request
>    * error_description: ['Le query param path est absent ou mal formaté']
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/jmkerloch/dev/ign/gpf-iti-scripts/gpf_iti_scripts/tests_gpf_sdk.py", line 536, in <module>
>     upload = upload_with_api(
>   File "/home/jmkerloch/dev/ign/gpf-iti-scripts/gpf_iti_scripts/tests_gpf_sdk.py", line 115, in upload_with_api
>     upload.api_push_data_file(local_path, api_path)
>   File "/home/jmkerloch/dev/ign/gpf-iti-scripts/.venv/lib/python3.10/site-packages/sdk_entrepot_gpf/store/Upload.py", line 47, in api_push_data_file
>     ApiRequester().route_upload_file(
>   File "/home/jmkerloch/dev/ign/gpf-iti-scripts/.venv/lib/python3.10/site-packages/sdk_entrepot_gpf/io/ApiRequester.py", line 285, in route_upload_file
>     return self.route_request(route_name, route_params=route_params, method=method, params=params, data=data, files=o_dict_files)
>   File "/home/jmkerloch/dev/ign/gpf-iti-scripts/.venv/lib/python3.10/site-packages/sdk_entrepot_gpf/io/ApiRequester.py", line 103, in route_request
>     return self.url_request(s_url, method, params, data, files, d_header)
>   File "/home/jmkerloch/dev/ign/gpf-iti-scripts/.venv/lib/python3.10/site-packages/sdk_entrepot_gpf/io/ApiRequester.py", line 155, in url_request
>     raise GpfSdkError(s_message) from e_error
> sdk_entrepot_gpf.Errors.GpfSdkError: La requête formulée par le programme est incorrecte (Le query param path est absent ou mal formaté). Contactez le support.

Il est nécessaire de changer la méthode pour l'appel à la route d'ajout de données sur un upload. L'indication du chemin du fichier livré n'est plus dans le paramètre de la route mais dans l'url directement.

Voici un exemple de la route attendue maintenant :
`
{{baseUrl}}/datastores/:datastore/uploads/:upload/data?path=/bdtopo/BDTOPO_TRANSPORT_PARIS.gpkg`

**Comment by LudivineSchlegel** [comment]
Bonjour,
On vient de voir le problème ce matin de notre côté. Le problème ne concerne que la qualification, la modification n'ai pas présente en production.
Je suis entrain de faire la correction.

La question est posé coté développement géoplatforme pour savoir si c'est une réel évolution ou une erreur.

**Comment by LudivineSchlegel** [comment]
La modification est faite sur la branche "debug_upload"
La modification pour la GPF qualification n'est pas compatible avec la GPF production donc on ne peut pas publier une nouvelle version avec les modifications.

En attendant la mise en prod de la modification côté GPF, il faut utiliser le dépôt en locale, la documentation est disponible ici : [docs/development.md](https://github.com/Geoplateforme/sdk-entrepot/blob/prod/docs/development.md) en utilisant la branche "debug_upload"
