### ISSUE TITLE
Erreur du comportement DELETE lors de la recréation de l'offre

### ISSUE THREAD

**Issue by CorentinPeutin** [Geoplateforme/sdk-entrepot#57]
Bonjour,

Lorsque que l'on utilise dans le fichier de config :
```[offering]
behavior_if_exists=DELETE
```
Et que l'on souhaite créer une offre déjà existante, la suppresion de cette offre a bien lieu mais le programme ne semble pas attendre la fin de la suppression avant de lancer la création de la nouvelle offre ce qui génère un conflit dans l'entrepôt
Voici les logs de l'erreur : 
```INFO - Lancement de l'étape publication-itineraire-valhalla...
INFO - Résolution de l'action 'publication-itineraire-valhalla-0'...
INFO - Résolution de l'action 'publication-itineraire-valhalla-0' : terminée
INFO - Exécution de l'action 'publication-itineraire-valhalla-0'...
INFO - Création d'une offre...
ALERTE - Une donnée offre équivalente à Offering(id=d3d58089-45dc-4bba-b172-9ea457c91559, layer_name=test_bag_valhalla_01) va être supprimée puis recréée.
ERREUR FATALE - Impossible de créer l'offre il y a un conflict : 
La configuration est déjà publiée selon cette zone et ce contexte
```
Merci

**Comment by vsasyan-ignf** [comment]
cf. #29 où la fonctionnalité a été ajoutée : il faudra attendre un peu après la suppression à voir si une petite attend suffit ou s'il faut faire une boucle.

**Comment by LudivineSchlegel** [comment]
Disponible dans la version [v0.1.19](https://github.com/Geoplateforme/sdk-entrepot/releases/tag/v0.1.19)

Lors de la suppression de l'offre (`Offering.api_delete()`) on attend que la suppression soit effectuée avant de sortir de la fonction.
Au passage la valeur de `--behavior` pour les pour ConfigurationAction et OfferingAction est pris en compte dans la nouvelle version (donc plus besoin de modifier le fichier de configuration).

@CorentinPeutin Cette modification résout-elle le problème ?

**Comment by CorentinPeutin** [comment]
Bonjour,

C'est parfait, la nouvelle offre est bien créée après la fin de la suppression de la précédente. Et la valeur --behavior fonctionne bien.
Merci beaucoup
