### ISSUE TITLE
Utilisation de la route PUT /datastores/{{ _.datastore }}/offerings/ dans le SDK ?

### ISSUE THREAD

**Issue by CorentinPeutin** [Geoplateforme/sdk-entrepot#58]
Bonjour,

Est-ce qu'il serait intéressant de créer une action du SDK qui correspond à la route PUT /datastores/{{ _.datastore }}/offerings/ dans l'entrepôt ?
Elle permet de mettre à jour une offre sans devoir supprimer puis recréer cette offre.

Merci

**Comment by vsasyan-ignf** [comment]
Bonjour,

Effectivement il faut gérer le PUT pour les configurations (maj) et les offres (resync).

Nous allons réfléchir à comment traduire cela en actions côté SDK. L'objectif est d'avoir cela courant janvier ou début février au plus tard.

**Comment by LudivineSchlegel** [comment]
Bonjour,
Je vais commencer le développement pour ajouté l'action.
Dans le fichier de workflow l'action de synchronisation aura pour structure :

* Mise à jour selon ID de l'offre 
```jsonc
{
  "type": "synchronize-offering",
  // Id de l'entité à supprimer (erreur remontée par l'API si l'entité n'existe pas)
  "entity_id": "{uuid}"
}
```
* suppression par filtrage sur la liste des offres, possibilité de synchroniser plusieurs offres en même temps
```jsonc
{
  "type": "synchronize-offering",
  // Ou Critères pour la retrouver 
  "filter_infos": { ...  },
  // optionnel : Que faire plusieurs résultats ?  first => uniquement 1er de la liste; all => on prend tout (défaut); error => sortie en erreur du programme 
  "if_multi": "first|all|error"
}
```
Si aucun résultat, on sort en erreur.

Pour "filter_infos" voir les filtres possibles pour la requête [/datastores/{datastore}/offerings](https://data.geopf.fr/api/swagger-ui/index.html#/Configurations%20et%20publications/getAll_6). Si on a `"configuration" : "{uuid}"` c'est la requête  [/datastores/{datastore}/configurations/{configuration}/offerings](https://data.geopf.fr/api/swagger-ui/index.html#/Configurations%20et%20publications/getOfferings) qui sera utilisée dans l'attente que la filtration sur les configurations soit possible.

**Comment by LudivineSchlegel** [comment]
La version v0.1.20 est disponible. Les actions de synchronisation des offering sont utilisable.
@CorentinPeutin si la solution vous conviens je vous laisse fermer le ticket.

**Comment by CorentinPeutin** [comment]
La solution est parfaite. Merci beaucoup
