### ISSUE TITLE
Pouvoir supprimer les entitées depuis le workflow

### ISSUE THREAD

**Issue by LudivineSchlegel** [Geoplateforme/sdk-entrepot#63]
Il est utile de pouvoir supprimer dans un workflow une ou des entité(s). Pour l'instant limitation aux upload, stored_data, configuration et offering.
Le programme demandera la confirmation à l'utilisateur avant d'effectuer la suppression des entités.

Structure de l'action :
* suppression par ID de l'entité
```jsonc
{
    "type": "delete-entity",
    // Type de l'entité à supprimer (upload, stored_data, configuration, offering)
    "entity_type": "configuration",
    // Id de l'entité à supprimer
    "entity_id": "{uuid}",
    // Suppression en cascade autorisée ou pas ? par défaut à false
    "cascade": true,
    // Ok si non trouvés ? par défaut à true
    "not_found_ok": true,
}
```
* suppression par filtre sur la liste
```jsonc
{
    "type": "delete-entity",
    // Type de l'entité à supprimer (upload, stored_data, configuration, offering)
    "entity_type": "configuration",
    // Critères pour filtrer filter_infos et/ou filter_tags
    "filter_infos": { ... },
    "filter_tags": { ... },
    // Suppression en cascade autorisée ou pas ? par défaut à false
    "cascade": true,
    // Ok si non trouvés ? par défaut à true
    "not_found_ok": true,
    // Que faire plusieurs résultats ?  first => uniquement 1er de la liste; all => on prend tout (défaut); error => sortie en erreur du programme 
    "if_multi": "first|all|error",
}
```
pour filter_infos voir les possibilités des fonctions de liste des entités :
* upload: [/datastores/{datastore}/uploads](https://data.geopf.fr/api/swagger-ui/index.html#/Livraisons%20et%20v%C3%A9rifications/getAll_1)
* stored_data: [/datastores/{datastore}/stored_data](https://data.geopf.fr/api/swagger-ui/index.html#/Donn%C3%A9es%20stock%C3%A9es/getAll_2)
* configuration: [/datastores/{datastore}/configurations](https://data.geopf.fr/api/swagger-ui/index.html#/Configurations%20et%20publications/getAll_8)
* offering: [/datastores/{datastore}/offerings](https://data.geopf.fr/api/swagger-ui/index.html#/Configurations%20et%20publications/getAll_6)

**Comment by vsasyan-ignf** [comment]
Pour la suppression "par Id de l'entité", je ne mettrais pas de `not_found_ok` du tout : si l'entité n'existe pas l'utilisateur ne sera pas en mesure de fournir l'id à priori. Enfin en tout cas je ne vois pas le cas d'usage ?

**Comment by vsasyan-ignf** [comment]
> Le programme demandera la confirmation à l'utilisateur avant d'effectuer la suppression des entités.

Il faudrait que cela puisse être forcé pour éviter les actions utilisateur si on le souhaite (vu que le but est d'automatiser).

On peut ajouter un `confirm: true/false` par exemple ?

**Comment by LudivineSchlegel** [comment]
> Pour la suppression "par Id de l'entité", je ne mettrais pas de `not_found_ok` du tout : si l'entité n'existe pas l'utilisateur ne sera pas en mesure de fournir l'id à priori. Enfin en tout cas je ne vois pas le cas d'usage ?

Ce cas peut se présenter si l'uuid est mise en dure dans le workflow ou que l'entité est supprimée entre la résolution et récupération de l'entité pour la supprimée.

**Comment by LudivineSchlegel** [comment]
> > Le programme demandera la confirmation à l'utilisateur avant d'effectuer la suppression des entités.
> 
> Il faudrait que cela puisse être forcé pour éviter les actions utilisateur si on le souhaite (vu que le but est d'automatiser).
> 
> On peut ajouter un `confirm: true/false` par exemple ?

C'est ajouté à l'action.
