### ISSUE TITLE
suivi Vérification livraison CTRL+C

### ISSUE THREAD

**Issue by LudivineSchlegel** [Geoplateforme/sdk-entrepot#8]
Intercepter CTRL+C pendant le monitoring (qui actionne le lancement d'un callback donné en entrée du programme)
Par défaut :  sortie en stoppant les vérifications  (raise un erreur d'interruption volontaire)
pour le __main__ :  question : 
    * sortie => sortie du monitoring, ne pas arreter les vérifications
    * stopper la vérification => stopper toutes les vérifications en cours
    * "erreur de manipulation" => reprendre le suivi

(à harmoniser avec la gestion du CTRL+C dans le suivi des traitements #9 )

**Comment by LudivineSchlegel** [comment]
Dans l'état actuelle ne pose pas de question et non fonctionnel : essaye de supprimer l'upload pendant que les vérifications sont en cours.
=> à corrigé et développé

**Comment by LudivineSchlegel** [comment]
fait pour la version v0.1.19 => ça fonctionne

Pour validation de principe @VSasyan si on demande d’arrêter les vérifications les vérifications sont supprimer et la livraison est ouverte, si on rouvre pas automatiquement la livraison elle semble être terminé et les tests OK.

**Comment by vsasyan-ignf** [comment]
Ok pour moi
