### ISSUE TITLE
[BUG] suppression de fichier dans répertoire "data" dans une livraison

### ISSUE THREAD

**Issue by LudivineSchlegel** [Geoplateforme/sdk-entrepot#80]
J'ai une livraison avec un fichier `data/inpe.gpkg` que je veux supprimer.
J'ai une erreur :
>    * url: https://data.geopf.fr/api/datastores/.../uploads/.../data
>    * method: DELETE
>    * params: {'path': 'inpe.gpkg'}
>    * data: null
>    * response: {"error":"Not Found","error_description":["Il n'y a pas de fichier de donnée à l'emplacement cible"]}
>    * error: Not Found
>    * error_description: ["Il n'y a pas de fichier de donnée à l'emplacement cible"]

Le `path` dans la requête n'ai pas bon `'inpe.gpkg'` au lien de `data/inpe.gpkg`

Dans le code de la fonction `Upload.api_delete_data_file()` on à une exception pour un répertoire "data" : https://github.com/Geoplateforme/sdk-entrepot/blob/2fb25b138a9b91192352847a49dc8443b6af8237/sdk_entrepot_gpf/store/Upload.py#L64-L66

Toujours utile ou héritage d'un code ancien ?

**Comment by vsasyan-ignf** [comment]
Effectivement ça doit être un code ancien. Les listés commençaient par "data/" mais il ne fallait pas mettre ce préfixe au moment de la suppression...
