### ISSUE TITLE
Gestion des permission

### ISSUE THREAD

**Issue by LudivineSchlegel** [Geoplateforme/sdk-entrepot#93]
Création d'une classe `Permission` qui permet d'accéder au requête API

* liste: GET /datastores/{datastore}/permissions
* création:  POST /datastores/{datastore}/permissions
* détail: GET /datastores/{datastore}/permissions/{permission}
* suppression: DELETE /datastores/{datastore}/permissions/{permission}
* edition partiel: PATCH /datastores/{datastore}/permissions/{permission}

**Comment by vsasyan-ignf** [comment]
Je ferme vu que la #103 traite ce ticket.
