### ISSUE TITLE
Pouvoir ajouté une permission sur une offre dapuis le workflow

### ISSUE THREAD

**Issue by LudivineSchlegel** [Geoplateforme/sdk-entrepot#94]
Il est utile de pouvoir ajouter une permission sur une offre dans un workflow, notamment pour pouvoir visualiser les offre privé.
Correspond à la requête [POST /datastores/{datastore}/permissions](https://data.geopf.fr/api/swagger-ui/index.html#/Gestion%20des%20permissions/create_2)

Structure de l'action dans le workflow :

```json
{
    "type": "permission",
    "body_parameters": {
        "end_date": "2025-01-29T15:30:00Z",
        "licence": "Validation $config_gpf",
        "offerings": [
            "$offering_gpf"
        ],
        "type": "COMMUNITY",
        "only_oauth": false,
        "communities": [
        "57f61baf-65dc-4079-8b6f-bafe66daad38"
        ]
    }
}
```

**Comment by vsasyan-ignf** [comment]
Je ferme vu que la #103 résout ce ticket.
