### ISSUE TITLE
Gestion des Key

### ISSUE THREAD

**Issue by LudivineSchlegel** [Geoplateforme/sdk-entrepot#96]
Création d'une classe `Key` qui permet d'accéder au requête API :

* liste: GET [/users/me/keys](https://data.geopf.fr/api/swagger-ui/index.html#/Utilisateurs/getUserKeys)
* création:  POST [/users/me/keys](https://data.geopf.fr/api/swagger-ui/index.html#/Utilisateurs/createUserKey)
* suppression: DELETE [/users/me/keys/{key}](https://data.geopf.fr/api/swagger-ui/index.html#/Utilisateurs/deleteKey)
* édition total: PATCH [/users/me/keys/{key}](https://data.geopf.fr/api/swagger-ui/index.html#/Utilisateurs/patchKey)

:warning: Attention route de détail non disponible ! :warning:

**Comment by vsasyan-ignf** [comment]
Classe Key ok. Il reste à gérer la création de clef via le cli.
